config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :subprojects, class_name: "Project", foreign_key: "parent_project_id", dependent: :destroy
  belongs_to :parent_project, class_name: "Project", optional: true

  has_many :tasks, dependent: :destroy

  validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  has_many :subtasks, class_name: "Task", foreign_key: "parent_task_id", dependent: :destroy
  belongs_to :parent_task, class_name: "Task", optional: true

  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(parent_project_id: nil)
    @project = Project.new
    @project_new = Project.new
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.where(parent_project_id: nil)
    @project_new = Project.new
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :parent_project_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project, only: [:edit, :create, :update, :complete, :destroy]
  before_action :set_task, only: [:edit, :update, :complete, :destroy]

  # def index
  #   @tasks = Task.all
  # end

  # def show
  # end

  # def new
  #   @task = Task.new
  # end

  def edit
  end

  def create
    # @task = Task.new(task_params)
    @task = @project.tasks.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to @project, notice: 'Task was successfully created.' }
        # format.json { render :show, status: :created, location: @task }
      else
        format.html { render "projects/show" }
        # format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @project, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete
    respond_to do |format|
      @task.update(complete_params)
      format.html { redirect_to @project, notice: 'Task was successfully completed.' }
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Task was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    # @task = Task.find(params[:id])
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:project_id, :description, :date, :time, :priority, :parent_task_id)
  end

  def complete_params
    params.require(:complete_status).permit(:completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <title>Ttbd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <%# if project.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>-->

<!--      <ul>-->
      <%# project.errors.full_messages.each do |message| %>
<!--        <li><%#= message %></li>-->
      <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

    <%= form.text_field :title, placeholder: 'Add project', 'data-role' => 'input' %>

    <%= form.collection_select(:parent_project_id, Project.all, :id, :title, :prompt => true) %>

    <%= form.submit :'Submit' %>

<% end %>

app/views/projects/_project.html.erb
<ul data-role="treeview">
  <li data-caption="Projects">
    <ul>
      <% @projects.each do |project| %>
        <li >
          <%= link_to "#{project.title}", project %>

          <% unless project.tasks.count.zero? %>
            <span class="badge inline"><%= project.tasks.count %></span>
          <% end %>

          <span style="float:right;">
            <%= link_to edit_project_path(project) do %>
              edit
            <% end %>
            <%= link_to project, method: :delete, data: {confirm: 'Are you sure?'} do %>
              delete
            <% end %>
          </span>

          <% if project.subprojects.any? %>
            <% project.subprojects.each do |subproject_1| %>
              <ul>
                <li>
                  <%= link_to "#{subproject_1.title}", subproject_1 %>

                  <% unless subproject_1.tasks.count.zero? %>
                    <span class="badge inline"><%= subproject_1.tasks.count %></span>
                  <% end %>

                  <span style="float:right;">
                    <%= link_to edit_project_path(subproject_1) do %>
                      edit
                    <% end %>

                    <%= link_to subproject_1, method: :delete, data: {confirm: 'Are you sure?'} do %>
                      delete
                    <% end %>
                  </span>

                  <% if subproject_1.subprojects.any? %>
                    <% subproject_1.subprojects.each do |subproject_2| %>
                      <ul>
                        <li>
                          <%= link_to "#{subproject_2.title}", subproject_2 %>

                          <% unless subproject_2.tasks.count.zero? %>
                            <span class="badge inline"><%= subproject_2.tasks.count %></span>
                          <% end %>

                          <span style="float:right;">
                            <%= link_to edit_project_path(subproject_2) do %>
                              edit
                            <% end %>

                            <%= link_to subproject_2, method: :delete, data: {confirm: 'Are you sure?'} do %>
                              delete
                            <% end %>
                          </span>

                          <% if subproject_2.subprojects.any? %>
                            <% subproject_2.subprojects.each do |subproject_3| %>
                              <ul>
                                <li>
                                  <%= link_to "#{subproject_3.title}", subproject_3 %>

                                  <% unless subproject_3.tasks.count.zero? %>
                                    <span class="badge inline"><%= subproject_3.tasks.count %></span>
                                  <% end %>

                                  <span style="float:right;">
                                    <%= link_to edit_project_path(subproject_3) do %>
                                      edit
                                    <% end %>

                                    <%= link_to subproject_3, method: :delete, data: {confirm: 'Are you sure?'} do %>
                                      delete
                                    <% end %>
                                  </span>
                                </li>
                              </ul>
                            <% end %>
                          <% end %>
                        </li>
                      </ul>
                    <% end %>
                  <% end %>
                </li>
              </ul>
            <% end %>
          <% end %>
        </li>
      <% end %>
      <li>
        <button class="button flat-button" id="collapse_toggle_edit">+ Edit project</button>
        <div class="pos-relative">
          <div data-role="collapse"
               data-collapsed="true"
               data-toggle-element="#collapse_toggle_edit">
            <%= render 'form', project: @project unless @project.id.nil?  %>
          </div>
        </div>
      </li>
      <li>
        <button class="button flat-button" id="collapse_toggle_add">+ Add project</button>
        <div class="pos-relative">
          <div data-role="collapse"
               data-collapsed="true"
               data-toggle-element="#collapse_toggle_add">
            <%= render 'form', project: @project_new %>
          </div>
        </div>
      </li>
    </ul>
  </li>
</ul>

<%#= link_to new_project_path do %>
<!--  +-->
<%# end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<div class="grid">
  <div class="row">
    <div class="cell-3">
      <div>
        <%= render 'projects/project' %>
      </div>
    </div>
    <div class="cell-9">
      <div>cell-9</div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<div class="grid">
  <div class="row">
    <div class="cell-3">
      <div>
        <%= render 'projects/project' %>
      </div>
    </div>
    <div class="cell-9">
      <div>
        <%= render 'tasks/task' %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@project, @project.tasks.build], local: true) do |form| %>
  <%# if @task && @task.errors.any? %>
  <!--    <div id="error_explanation">-->
  <!--      <h2><%#= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>-->

  <!--      <ul>-->
  <%# @task.errors.full_messages.each do |message| %>
  <!--          <li><%#= message %></li>-->
  <%# end %>
  <!--      </ul>-->
  <!--    </div>-->
  <%# end %>

  <%= form.text_field :description, placeholder: 'Add task' %>
  <%= form.collection_select(:parent_task_id, Task.all, :id, :description, :prompt => true) %>
  <%= form.text_field :date, 'data-role' => 'calendarpicker' %>
  <%= form.text_field :time, 'data-role' => "timepicker", 'data-seconds' => "false" %>
  <%= form.select :priority, (1..5) %>
  <%= form.submit :'Submit' %>
<% end %>

app/views/tasks/_task.html.erb
<ul data-role="treeview">

    <% @project.tasks.each do |task| %>
      <li>
        <% if task.completed %>
          <%= link_to complete_project_task_path(task.project, task, complete_status: {completed: false}), method: :patch do %>
            <input type="checkbox" data-role="checkbox" checked>
          <% end %>
          <strike><%= task.description %></strike>
          <%= link_to 'Destroy', [task.project, task], method: :delete, data: {confirm: 'Are you sure?'} %>
        <% else %>
          <%= link_to complete_project_task_path(task.project, task, complete_status: {completed: true}), method: :patch do %>
            <input type="checkbox" data-role="checkbox">
          <% end %>
          <%= task.description %>
          <%= link_to 'Edit', edit_project_task_path(task.project, task) %> |
          <%= link_to 'Destroy', [task.project, task], method: :delete, data: {confirm: 'Are you sure?'} %>
        <% end %>
        <%= task.date %>
        <% unless task.time.nil? %>
          <%= task.time.strftime("%H:%M") %>
        <% end %>
        <%= task.priority %>

        <% if task.subtasks.any? %>
          <% task.subtasks.each do |subtask_1| %>
            <ul>
              <li>
                <% if subtask_1.completed %>
                  <%= link_to complete_project_task_path(subtask_1.project, subtask_1, complete_status: {completed: false}), method: :patch do %>
                    <input type="checkbox" data-role="checkbox" checked>
                  <% end %>
                  <strike><%= subtask_1.description %></strike>
                  <%= link_to 'Destroy', [subtask_1.project, subtask_1], method: :delete, data: {confirm: 'Are you sure?'} %>
                <% else %>
                  <%= link_to complete_project_task_path(subtask_1.project, subtask_1, complete_status: {completed: true}), method: :patch do %>
                    <input type="checkbox" data-role="checkbox">
                  <% end %>
                  <%= subtask_1.description %>
                  <%= link_to 'Edit', edit_project_task_path(subtask_1.project, subtask_1) %> |
                  <%= link_to 'Destroy', [subtask_1.project, subtask_1], method: :delete, data: {confirm: 'Are you sure?'} %>
                <% end %>
                <%= subtask_1.date %>
                <% unless subtask_1.time.nil? %>
                  <%= subtask_1.time.strftime("%H:%M") %>
                <% end %>
                <%= subtask_1.priority %>
              </li>
            </ul>
          <% end %>
        <% end %>
      </li>
    <% end %>
    <li><%= render 'tasks/form', project: @project %></li>
    <li></li>
</ul>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%#= render 'form', task: @task %>

<%= form_with(model: [ @project, @task ], local: true) do |form| %>
  <% if @task && @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, (1..5) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', project_path(@project) %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Description</th>
      <th>Date</th>
      <th>Time</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.project %></td>
        <td><%= task.description %></td>
        <td><%= task.date %></td>
        <td><%= task.time %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @task.project %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @task.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @task.time %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<%= link_to 'Edit', edit_project_task_path(@task) %> |
<%= link_to 'Back', project_tasks_path %>